### ISSUE TITLE
A problem during installation in python modules.

### ISSUE THREAD

**Issue by wufan-tb** [jadarve/optical-flow-filter#10]
I was trying install the python module, but after I input "python setup.py install" I got an error: Unable to find vcvarsall.bat(seen in the picture). So how can I fix it. Any help will be appreciate.

![1](https://user-images.githubusercontent.com/34300920/33757952-51dc58d6-dc37-11e7-9589-474feb371704.jpg)

**Comment by jadarve** [comment]
I haven't tried building the python wrappers on Windows, just Linux. Maybe [this link](https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat) can help you.

**Comment by jadarve** [comment]
Closing this one as being inactive for a long time.
