### ISSUE TITLE
Error occuring in setup.py ,due to which ipython notebook is notworking

### ISSUE THREAD

**Issue by pranavpawar3** [jadarve/optical-flow-filter#11]
1.The error which is occurring again and again in the command  `sudo python setup.py install` is 
Traceback (most recent call last):
 ```
 File "setup.py", line 17, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
```

2.Also the `python setup.py build `command is not installing or building actually. The command just gets executed within 2-3 seconds. So i guess it's not doing anything in actual. When the command was executed for the first time two warnings were printed several times , 

```
 warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \

```
and after executing that command again 
It is printing following lines
```
running build
running build_py
running build_ext
```
The cuda version 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

```
and the os is 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```
So how to fix this ?
And is there any other method to achieve the same results for optical-flow-filter?

**Comment by jadarve** [comment]
what is your cython version?

```
cython --version
```

**Comment by pranavpawar3** [comment]
cython version is 0.28.2

**Comment by jadarve** [comment]
I upgraded my machine to Cython 0.28.2 and now I'm having trouble compiling the Python wrappers. When I run `ptyhon setup.py build` I get get following error:

```
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    extList = cythonize(createExtension(mod[0], mod[1]), compiler_directives=cython_directives)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 897, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 719, in create_extension_list
    elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
  File "/usr/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/local/lib/python2.7/dist-packages/backports_abc.py", line 66, in __subclasshook__
    mro = C.__mro__
AttributeError: class Extension has no attribute '__mro__'
```

I will check what's happening and fix it.

**Comment by pranavpawar3** [comment]
Yeah sure, do let me know about it.

**Comment by jadarve** [comment]
This is a problem with Cython 0.28.2. I tried downgrading to version 0.23.5 and the build process completes successfully. This is a known issue: https://github.com/cython/cython/issues/1507

You can downgrade Cython as follows:

Uninstall current version:

```
sudo pip uninstall cython
```
or

```
sudo apt remove python-cython
```
depending on how you installed it.

Then you can install the proper version as follows

```
sudo pip install cython==0.23.5
```

**Comment by pranavpawar3** [comment]
I downgraded Cython, but still it is showing the same error after `sudo python setup.py install.` Also the same warnings are coming after running command `python setup.py build`.  One more thing, when i executed the command` sudo pip uninstall cython` it was showing following error;
`sudo: pip: command not found
`
so that is why i used `pip uninstall cython` and thus it got uninstalled. Same happened for `sudo pip cython==0.23.5 and i fixed it in the same way.

**Comment by jadarve** [comment]
Could you confirm the new Cython version? From the comment above, you didn't have `pip` installed in your machine. As mentioned above, using Cython 0.23.5 works fine.

**Comment by pranavpawar3** [comment]
Sorry for the late reply Jaden, but the issue is solved now, one of my senior solved it. Thanks for your time and help!!!
