### ISSUE TITLE
A real time optical flow algorithm implemented on GPU is it CPU compatible? 

### ISSUE THREAD

**Issue by MuhammadKA** [jadarve/optical-flow-filter#12]
Can I run this code on laptop using core i7 CPU?
I am sorry if my question is trivial, but is the code implementation has something special to work on GPU only?

**Comment by jadarve** [comment]
Hi, you might use the pure python implementation in https://github.com/jadarve/optical-flow-filter/blob/master/python/flowfilter/flowfilter.py but it will run slower than the GPU version.

Alternatively, I am working on a new version of the algorithm that can run on any Vulkan enabled GPU https://github.com/jadarve/lluvia/issues/52.

**Comment by jadarve** [comment]
Please reopen the issue if you have any other questions.
