### ISSUE TITLE
Optical flow always equals zero?

### ISSUE THREAD

**Issue by m-zainkhawaja** [jadarve/optical-flow-filter#6]
Hi Juan,

Thanks for sharing your code. I'm trying to incorporate your optical flow calculations in my project and have followed your webcam demo to calculate flow using OpenCV. I'm acquiring camera image frames from a pre-recorded video for my processing and always get a flow vector of zero magnitude. I also get the following message on my console:

DeltaFlowFilter::compute(): fisrt load
FlowFilter::compute(): fisrt load
DeltaFlowFilter::compute(): fisrt load
DeltaFlowFilter::compute(): fisrt load
FlowFilter::compute(): fisrt load

This message repeats itself throughout video processing. Do you have any advice? I get the feeling that only a single optical flow is being calculated for the initial frame and state propagation isn't taking place. Thanks for your help!

**Comment by jadarve** [comment]
Hi,

Thanks for using my code :)

Could you share the code of the inner loop where you acquire the camera frames and compute the optical flow. From the continuous print of `FlowFilter::compute(): fisrt load` my guess is that you are instantiating the PyramidalFlowFilter object inside the capture loop, thus resetting the algorithm every time a new frame arrives.

Inside the inner loop, you should just need to call [(see example)](https://github.com/jadarve/optical-flow-filter/blob/master/demos/flowWebCam/src/flowWebCam.cpp#L111)
```
// transfer image to flow filter and compute
filter.loadImage(hostImageGray);
filter.compute();
```
to transfer images to the algorithm and compute the optical flow.

**Comment by m-zainkhawaja** [comment]
Hi Juan,

Thank you for your comment, I made the requisite edits as per your example. I was indeed instantiating the PyramidalFlowFilter inside the loop and have fixed this.  However, I am now getting another issue, this time related to cuda. I am using Cuda-8.0.  I started commenting out lines to see what caused the issue, and `filter.compute();` seems to be causing:
ERROR: invalid resource handle at //optical-flow-filter/src/optical-flow-filter/src/gpu/pipeline.cu : 64
and my code then fails to compile.

None of my other code is currently relying on a gpu and the structure of the code is as per your example:
`    // Optical flow
    cv::Mat fcolor(height, width, CV_8UC4);
    cv::Mat image_prev_gray(height,width, CV_8UC1);

    flowfilter::image_t hostImageGray;
    flowfilter::image_t hostFlowColor;

    wrapCVMat(image_prev_gray, hostImageGray);
    wrapCVMat(fcolor, hostFlowColor);

    //#################################
    // Filter parameters
    //#################################
    float maxflow = 40.0f;
    std::vector<float> gamma = {500.0f, 50.0f, 5.0f};
    std::vector<int> smoothIterations = {2, 8, 20};

    //#################################
    // Filter creation with
    // 3 pyramid levels

    flowfilter::gpu::PyramidalFlowFilter filter(height, width, 3);
    filter.setMaxFlow(maxflow);
    filter.setGamma(gamma);
    filter.setSmoothIterations(smoothIterations);

    //#################################
    // To access optical flow
    // on the host
    //#################################
    cv::Mat flowHost(height, width, CV_32FC2);
    flowfilter::image_t flowHostWrapper;
    wrapCVMat(flowHost, flowHostWrapper);

    flowfilter::gpu::FlowToColor flowColor(filter.getFlow(), maxflow);`

Then in the loop:
acquire image from camera and convert to grayscale (image_prev_gray), filter.load(hostImageGray), filter.compute(), similarly with fcolor, and then display the grayscale image and color.

Thank you for your help.

**Comment by jadarve** [comment]
That's strange. Does the flowWebCam demo give the same error? just to rule out if it is a problem of CUDA 8.

**Comment by m-zainkhawaja** [comment]
Yes, flowWebCam also produces strange errors. It displays an image for one frame and then immediately shuts down.

**Comment by jadarve** [comment]
I just tested the flowWebCam demo and it crashes using CUDA 8 on Ubuntu 14.04 and OpenCV 3.2. I will have a look what the problem is.

**Comment by jadarve** [comment]
Could you build and run the flowProfiler project with the following parameters?

```
./flowProfiler 480 640 2 4 1000
```

In my computer it runs fine.

**Comment by jadarve** [comment]
I found the problem on my machine. It turns out OpenCV waitKey(delay) always returns 255 in [line 132](https://github.com/jadarve/optical-flow-filter/blob/master/demos/flowWebCam/src/flowWebCam.cpp#L132). Thus, the for loop only iterates once, not showing any result and the program stops.

Commenting that line and replacing it by
```
cout << "waitKey: " << waitKey(10) << endl;
```
solves the problem. You will need to kill the program from the terminal. Sometimes the program will not start again because the webcam is reported to being used. Unplugging it and plugging it again fixes that.

Could you verify if this solves the problem?

**Comment by m-zainkhawaja** [comment]
Hello Juan,
Running flowProfiler with your specified input arguments from the terminal produced a list of numbers in the range approx (0.7 - 1.0) which ended after about 100 numbers had been produced. This took less than a second. I'm not sure if this is the correct behaviour. I commented out line 132 in flowWebcam as per you instructions and it works just fine! Thank you so much for your helpful comments. Have you considered benchmarking your optical flow on KITTI or Middlebury?
