### ISSUE TITLE
Question about paper's equation (17).

### ISSUE THREAD

**Issue by dragonkao730** [jadarve/optical-flow-filter#7]
Hi Juan,

Sorry, can I ask some question about the paper here? 
Why Equation (17) uses `^h\Delta\Phi` rather than `^h\Phi` ?
I have not traced your code yet but this has already perplexed me for a long time.

Your paper is great, and code work fine to me! Thanks for your help!

**Comment by dragonkao730** [comment]
I think I miss understand...

**Comment by jadarve** [comment]
Hi, did you solve the issue yourself?

**Comment by dragonkao730** [comment]
Not really ...

I have closed it because I traced the code and found that it just implements equation (17), so the equation in your paper must be right.

I think `^h\Delta\Phi` should be `^h\Phi` because:

<a href="https://www.codecogs.com/eqnedit.php?latex=^{H-1}a_1^{k&plus;1}&space;\cdot&space;^{H-1}\Phi^{k&plus;1}&space;&plus;&space;^{H-1}a_0^{K&plus;1}&space;-&space;^{H-1}a_0^{K&plus;}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?^{H-1}a_1^{k&plus;1}&space;\cdot&space;^{H-1}\Phi^{k&plus;1}&space;&plus;&space;^{H-1}a_0^{K&plus;1}&space;-&space;^{H-1}a_0^{K&plus;}" title="^{H-1}a_1^{k+1} \cdot ^{H-1}\Phi^{k+1} + ^{H-1}a_0^{K+1} - ^{H-1}a_0^{K+}" /></a>

in equation (12) is exactly same as _brightness constancy constraint_ on [wiki](https://en.wikipedia.org/wiki/Optical_flow):

<a href="https://www.codecogs.com/eqnedit.php?latex=I(x,&space;y,&space;z)&space;=&space;I(x&space;&plus;&space;\Delta&space;x,&space;y&space;&plus;&space;\Delta&space;y,&space;t&space;&plus;&space;\Delta&space;t)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I(x,&space;y,&space;z)&space;=&space;I(x&space;&plus;&space;\Delta&space;x,&space;y&space;&plus;&space;\Delta&space;y,&space;t&space;&plus;&space;\Delta&space;t)" title="I(x, y, z) = I(x + \Delta x, y + \Delta y, t + \Delta t)" /></a>

<a href="https://www.codecogs.com/eqnedit.php?latex=\nabla&space;I^T&space;\cdot&space;\vec{V}&space;&plus;&space;I_t&space;=&space;0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\nabla&space;I^T&space;\cdot&space;\vec{V}&space;&plus;&space;I_t&space;=&space;0" title="\nabla I^T \cdot \vec{V} + I_t = 0" /></a>

but equation (17) do not use the **full flow**... so I can't understand the equation.

If you can explain it to me, I will be super thankful.

Thanks for your help!

**Comment by jadarve** [comment]
The shape of Eq. (17) has to do with the filtering nature of the algorithm and the pyramidal structure. I will use Fig. (2) for my explanation.

The simplest filter loop (Fig 2.a) is at top level H-1. There, the **full optical flow** is predicted (Eq. 8) and estimated (Eq. 12), and the estimation equation is indeed the *brightness constancy constraint* plus a regularization term.

At lower pyramid levels (Fig 2.b), the first step is to compute the **full flow** for level `h`. This `^h\Phi^k` is used to predict the values of the **image** <a href="https://www.codecogs.com/eqnedit.php?latex=^ha_0^{k&plus;}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^ha_0^{k&plus;}" title="^ha_0^{k+}" /></a> and **delta flow** <a href="https://www.codecogs.com/eqnedit.php?latex=^h\Delta&space;\Phi^{k&plus;}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^h\Delta&space;\Phi^{k&plus;}" title="^h\Delta \Phi^{k+}" /></a> before the new measurements at time `k+1` arrive. Notice that <a href="https://www.codecogs.com/eqnedit.php?latex=^ha_0^{k&plus;}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^ha_0^{k&plus;}" title="^ha_0^{k+}" /></a> is not the image at previous time step, but something closer to <a href="https://www.codecogs.com/eqnedit.php?latex=^ha_0^{k&plus;1}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^ha_0^{k&plus;1}" title="^ha_0^{k+1}" /></a>. Under the *brightness constancy constraint*, any difference between the image at time k+1 and <a href="https://www.codecogs.com/eqnedit.php?latex=^ha_0^{k&plus;}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^ha_0^{k&plus;}" title="^ha_0^{k+}" /></a> can be attributed to some small displacement  <a href="https://www.codecogs.com/eqnedit.php?latex=^h\Delta&space;\Phi^{k&plus;1}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?^h\Delta&space;\Phi^{k&plus;1}" title="^h\Delta \Phi^{k+1}" /></a> which is what we want to calculate in the estimation stage (Eq 17).

I hope this helps.

**Comment by jadarve** [comment]
I'm closing this issue now.
