### ISSUE TITLE
error: libflowfilter_gpu.so

### ISSUE THREAD

**Issue by joyyang1215** [jadarve/optical-flow-filter#8]
when I run ./flowWebCam, errors occured.
`./flowWebCam: error while loading shared libraries: libflowfilter_gpu.so: cannot open shared object file: No such file or directory`
Any help?
Best,
Joy Yang

**Comment by TirelessTinkerer** [comment]
@joyyang1215 
quick solution:
in demo/flowWebCam/CMakeLists.txt:
set( LIBS /usr/local/lib/libflowfilter_gpu.so)

**Comment by jadarve** [comment]
Closing this one as being solved.
